/** List of tag icon filenames */
export const tagIcons = [
  'active-user',
  'audit',
  'baggage-2',
  'category',
  'external-link',
  'discord',
  'github',
  'hacks',
  'level',
  'linkedin',
  'location',
  'money',
  'monthly-volume',
  'revenue',
  'suitcase',
  'token',
  'tvl',
  'twitter',
  'telegram',
  'users-three',
  'website',
  'funding',
] as const;
