import { JobPost } from '@jobstash/shared/core';

import FeaturedJob from './featured-job';

const fakeFeaturedJobs: JobPost[] = [
  {
    id: '145780df-a352-4420-98f9-20adbb6cf630',
    url: 'https://boards.greenhouse.io/oasisnetwork/jobs/4298160005',
    access: 'public',
    title: 'Senior Software Engineer, Core Platform',
    summary:
      'The Oasis Protocol Foundation is looking for a Senior Software Engineer to design, develop, test, deploy and maintain the systems of our blockchain ecosystem.',
    description:
      'As a Senior Software Engineer, you will be responsible for the core network protocol, distributed systems architecture, cryptosystems, and developer tools. You will manage project priorities, fast-paced deadlines and concrete deliverables. You will also participate in design and code reviews, including from the Oasis Foundation team and the broader open-source community.',
    requirements: [
      'BS degree in Computer Science or a similar technical field of study',
      '5+ years of software development experience',
      'Distributed systems experience',
      'Strong knowledge of CS fundamentals',
      'Proficient in Go and/or Rust',
      'Ability to lead projects to timely milestones',
      'Interest in Privacy & Confidentiality',
      'MUST: fluent in English',
    ],
    responsibilities: [
      'Design, develop, test, deploy and maintain the systems of our blockchain ecosystem, including the core network protocol, distributed systems architecture, cryptosystems, and developer tools.',
      'Manage project priorities, fast-paced deadlines and concrete deliverables.',
      'Participate in design and code reviews, including from the Oasis Foundation team and the broader open-source community.',
      'Improve engineering standards, tooling and processes.',
    ],
    shortUUID: 'oiTN5l',
    minimumSalary: null,
    maximumSalary: null,
    salary: null,
    seniority: '3',
    benefits: [],
    culture: null,
    location: 'Slovenia - Remote',
    salaryCurrency: 'USDT',
    paysInCrypto: true,
    offersTokenAllocation: null,
    timestamp: 1_696_420_041_590,
    tags: [
      {
        name: 'Engineering Standards',
        id: 'aa14af87-3053-468d-87f6-ab8d55039828',
        normalizedName: 'engineeringstandards',
      },
      {
        name: 'Go',
        id: '7e8ef9e5-af62-496d-bae2-6d7c8f3be465',
        normalizedName: 'go',
      },
      {
        name: 'Software Development',
        id: '2bcce17b-871c-4833-be86-7bb9240ee0ba',
        normalizedName: 'softwaredevelopment',
      },
      {
        name: 'Design Review',
        id: '89b7f296-6909-4a44-962f-591590c3e478',
        normalizedName: 'designreview',
      },
      {
        name: 'Distributed Systems',
        id: '92b609f8-0e20-48d8-9b4e-d5ea29f6e25b',
        normalizedName: 'distributedsystems',
      },
      {
        name: 'Rust',
        id: '3269c47d-2de5-4fed-9ed9-87a9681896da',
        normalizedName: 'rust',
      },
      {
        name: 'Project Management',
        id: '7e9f3307-1be7-4ca2-9b5b-592e62471d9b',
        normalizedName: 'projectmanagement',
      },
      {
        name: 'Processes',
        id: '0b405c72-79cc-4fe2-af3f-aee1411c1773',
        normalizedName: 'processes',
      },
      {
        name: 'Code Review',
        id: 'a9f8365b-dd69-43be-97da-23658359a6f6',
        normalizedName: 'codereview',
      },
      {
        name: 'Tooling',
        id: 'c2b62a39-438a-47f1-82f3-70c821d43178',
        normalizedName: 'tooling',
      },
    ],
    commitment: 'FULL_TIME',
    locationType: 'REMOTE',
    classification: 'ENGINEERING',
    organization: {
      grants: [],
      hasUser: false,
      atsClient: null,
      summary:
        'Oasis Protocol Foundation is the legal entity behind the Oasis Protocol',
      github: null,
      website: 'https://oasisprotocol.org/',
      aggregateRating: 4.2,
      reviewCount: 69,
      ecosystems: [],
      projects: [
        {
          github: null,
          website: 'https://oasisprotocol.org/',
          chains: [],
          telegram: 'oasisprotocolcommunity',
          description:
            'Oasis Protocol Foundation is a privacy-enabled blockchain platform for open finance and a responsible data economy.',
          twitter: null,
          discord: 'https://discord.com/invite/BQCxwhT5wS',
          docs: 'https://oasisprotocol.org/developers',
          hacks: [],
          name: 'Oasis',
          normalizedName: 'oasis',
          id: 'e65d7d5f-68f6-41f2-badc-24cfb636c1c1',
          category: 'Network',
          audits: [
            {
              date: 1_633_219_200_000,
              link: 'https://files.safe.de.fi/safe/files/audit/pdf/Oasis_Smart_Contract_Security_Audit_Report.pdf',
              name: 'Smart contracts',
              id: 'feb6402e-186d-457c-acab-a498b1d6a39a',
              defiId: '7215',
              techIssues: null,
            },
          ],
          tokenSymbol: null,
          tvl: null,
          monthlyVolume: null,
          monthlyFees: null,
          monthlyRevenue: null,
          monthlyActiveUsers: null,
          logo: null,
          ecosystems: [],
          defiLlamaId: null,
          defiLlamaSlug: null,
          defiLlamaParent: null,
          orgIds: ['107'],
        },
      ],
      createdTimestamp: 1_696_420_033_962,
      telegram: 'oasisprotocolcommunity',
      description:
        'Oasis Protocol Foundation is a privacy-enabled blockchain platform for open finance and a responsible data economy.',
      investors: [],
      fundingRounds: [
        {
          date: 1_531_094_400,
          raisedAmount: 45,
          roundName: 'Unknown',
          id: '40c0e6cf-ab41-4588-835b-2c68be1fc1bd',
        },
      ],
      updatedTimestamp: 1_696_431_559_831,
      orgId: '107',
      twitter: null,
      discord: 'https://discord.com/invite/BQCxwhT5wS',
      docs: 'https://docs.oasis.io/',
      name: 'Oasis Protocol Foundation',
      normalizedName: 'oasis-protocol-foundation',
      aliases: ['Oasis Labs'],
      location: 'Singapore',
      id: '0d1be7c3-f6b1-4ab6-a903-255e8f0784bf',
      logoUrl: null,
      headcountEstimate: null,
    },
    project: null,
    featured: false,
    featureStartDate: null,
    featureEndDate: null,
    onboardIntoWeb3: false,
  },
  {
    id: '3b03f2e4-cefb-4df2-999d-79dabd70a720',
    url: 'https://boards.greenhouse.io/oasisnetwork/jobs/4307432005',
    access: 'public',
    title: 'Developer Relations Manager',
    summary:
      'Oasis Network is looking for a Developer Relations Manager to help developers and projects build and launch dApps using the Oasis Privacy Layer and the Oasis Sapphire, respond to technical questions, and build a strong Oasis developer community.',
    description:
      'As a Developer Relations Manager, you will be responsible for helping developers and projects to successfully build and launch dApps using the Oasis Privacy Layer and the Oasis Sapphire. You will respond to technical questions from developers and builders, solicit and respond to feedback from the Oasis developer community, and share feedback/insights with Product/Engineering. You will also host technical workshops at conferences/events and produce technical content.',
    requirements: [
      'Passionate about software development, Web3, privacy and building communities',
      'Bachelor degree in Computer Science or related Engineering fields',
      '3+ years of experience as a software developer or developer relations/advocate',
      'Has contributed to open source projects',
      'Strong technical experience with smart contract development, specifically in Solidity',
      'In-depth knowledge of the developer products and tooling market in Web3',
      'In-depth knowledge of Layer-1 blockchain networks and Web3 dApps',
      'Superb spoken and written English',
    ],
    responsibilities: [
      'Help developers and projects to successfully build and launch dApps using the Oasis Privacy Layer and the Oasis Sapphire',
      'Respond to technical questions from developers and builders',
      'Solicit and respond to feedback from Oasis developer community and share feedback/insights with Product/Engineering',
      'Build a strong Oasis developer community',
      'Host technical workshops at conferences/events and produce technical content',
      'Evangelize Oasis technologies, to Oasis community and the wider Web3 ecosystem',
      'Improve the overall quality and engagement of the Oasis developer community on channels such as Oasis Forum, Discord, etc.',
      'Collaborate with Marketing, Community and BD to grow developer engagement and onboard new developers',
    ],
    shortUUID: 'm2zfOf',
    minimumSalary: null,
    maximumSalary: null,
    salary: null,
    seniority: '3',
    benefits: [],
    culture: null,
    location: 'Remote',
    salaryCurrency: 'USDT',
    paysInCrypto: true,
    offersTokenAllocation: false,
    timestamp: 1_696_420_041_590,
    tags: [
      {
        name: 'tooling market',
        id: '50d347ae-ae8a-4296-9036-34598ce50639',
        normalizedName: 'toolingmarket',
      },
      {
        name: 'developer products',
        id: '35e6f5f5-a276-473b-b679-3b8a46bf77b9',
        normalizedName: 'developerproducts',
      },
      {
        name: 'Solidity',
        id: 'e2592ce8-b0be-454f-aada-6fd9cdf0e1ae',
        normalizedName: 'solidity',
      },
      {
        name: 'Engineering',
        id: 'f4cfda08-94a7-4639-abea-b86f7b2123e8',
        normalizedName: 'engineering',
      },
      {
        name: 'software development',
        id: 'c6ce8478-62cd-48d5-a263-4efa8902aeb5',
        normalizedName: 'softwaredevelopment',
      },
      {
        name: 'software developer',
        id: '0d9e6304-89cd-4263-9b73-f3f8c82d1fbc',
        normalizedName: 'softwaredeveloper',
      },
      {
        name: 'Computer Science',
        id: '4596e285-3723-4966-b981-129374d85373',
        normalizedName: 'computerscience',
      },
      {
        name: 'building communities',
        id: 'd31c1d59-f52e-466d-828b-f88bdc661f8e',
        normalizedName: 'buildingcommunities',
      },
      {
        name: 'Web3 dApps',
        id: '379d993f-68b6-4f64-b58e-f018871dd786',
        normalizedName: 'web3dapps',
      },
      {
        name: 'Layer-1 blockchain networks',
        id: 'f731704e-258b-4d52-abf8-88c84c835234',
        normalizedName: 'layer1blockchainnetworks',
      },
      {
        name: 'Web3',
        id: '819c0e1a-fc7d-446f-8e1f-c66e575cfa22',
        normalizedName: 'web3',
      },
      {
        name: 'English',
        id: '5c80107f-5d8f-44c4-8874-1ddf8f3c52f7',
        normalizedName: 'english',
      },
      {
        name: 'privacy',
        id: '8b0bb4d1-ab10-42df-b8ff-3e6e4d209980',
        normalizedName: 'privacy',
      },
      {
        name: 'developer relations',
        id: '4829697c-f8c8-4f49-96c9-987003f59398',
        normalizedName: 'developerrelations',
      },
      {
        name: 'advocate',
        id: '43470792-d290-4999-b7fc-3e8b2ce9574b',
        normalizedName: 'advocate',
      },
      {
        name: 'open source projects',
        id: 'a7c5d507-e0eb-44ef-8db1-abba2f78b61d',
        normalizedName: 'opensourceprojects',
      },
      {
        name: 'smart contract development',
        id: 'd7a1ff74-108e-4c11-a757-f9116d133fd7',
        normalizedName: 'smartcontractdevelopment',
      },
    ],
    commitment: 'FULL_TIME',
    locationType: 'REMOTE',
    classification: 'DEVREL',
    organization: {
      grants: [],
      hasUser: false,
      atsClient: null,
      summary:
        'Oasis Protocol Foundation is the legal entity behind the Oasis Protocol',
      github: null,
      website: 'https://oasisprotocol.org/',
      aggregateRating: 4.2,
      reviewCount: 69,
      ecosystems: [],
      projects: [
        {
          github: null,
          website: 'https://oasisprotocol.org/',
          chains: [],
          telegram: 'oasisprotocolcommunity',
          description:
            'Oasis Protocol Foundation is a privacy-enabled blockchain platform for open finance and a responsible data economy.',
          twitter: null,
          discord: 'https://discord.com/invite/BQCxwhT5wS',
          docs: 'https://oasisprotocol.org/developers',
          hacks: [],
          name: 'Oasis',
          normalizedName: 'oasis',
          id: 'e65d7d5f-68f6-41f2-badc-24cfb636c1c1',
          category: 'Network',
          audits: [
            {
              date: 1_633_219_200_000,
              link: 'https://files.safe.de.fi/safe/files/audit/pdf/Oasis_Smart_Contract_Security_Audit_Report.pdf',
              name: 'Smart contracts',
              id: 'feb6402e-186d-457c-acab-a498b1d6a39a',
              defiId: '7215',
              techIssues: null,
            },
          ],
          tokenSymbol: null,
          tvl: null,
          monthlyVolume: null,
          monthlyFees: null,
          monthlyRevenue: null,
          monthlyActiveUsers: null,
          logo: null,
          ecosystems: [],
          defiLlamaId: null,
          defiLlamaSlug: null,
          defiLlamaParent: null,
          orgIds: ['107'],
        },
      ],
      createdTimestamp: 1_696_420_033_962,
      telegram: 'oasisprotocolcommunity',
      description:
        'Oasis Protocol Foundation is a privacy-enabled blockchain platform for open finance and a responsible data economy.',
      investors: [],
      fundingRounds: [
        {
          date: 1_531_094_400,
          raisedAmount: 45,
          roundName: 'Unknown',
          id: '40c0e6cf-ab41-4588-835b-2c68be1fc1bd',
        },
      ],
      updatedTimestamp: 1_696_431_559_831,
      orgId: '107',
      twitter: null,
      discord: 'https://discord.com/invite/BQCxwhT5wS',
      docs: 'https://docs.oasis.io/',
      name: 'Oasis Protocol Foundation',
      normalizedName: 'oasis-protocol-foundation',
      aliases: ['Oasis Labs'],
      location: 'Singapore',
      id: '0d1be7c3-f6b1-4ab6-a903-255e8f0784bf',
      logoUrl: null,
      headcountEstimate: null,
    },
    project: null,
    featured: false,
    featureStartDate: null,
    featureEndDate: null,
    onboardIntoWeb3: false,
  },
];

const FeaturedJobs = () => (
  <div className="flex flex-col gap-4">
    <div className="flex w-full justify-between">
      <p>Featured Jobs</p>
      <p>View All</p>
    </div>
    <div className="flex gap-8 justify-around">
      {fakeFeaturedJobs.map((job) => (
        <FeaturedJob key={job.id} job={job} />
      ))}
    </div>
  </div>
);

export default FeaturedJobs;
