import {
  AuditTagIcon,
  ChainTagIcon,
  CoinsTagIcon,
  DiscordTagIcon,
  Dollar2TagIcon,
  DollarTagIcon,
  FoldersTagIcon,
  FundingTagIcon,
  GithubTagIcon,
  LinkedInTagIcon,
  LinkTagIcon,
  LocationTagIcon,
  RunTagIcon,
  SalaryTagIcon,
  SeniorTagIcon,
  ShoppingBagTagIcon,
  SkullTagIcon,
  TeamSizeTagIcon,
  TwitterTagIcon,
  UtcTagIcon,
  WebsiteTagIcon,
} from '~/features/unstyled-ui/icons';

// UNOFFICIAL: temporary solution for tag icons
export const tagIconMap = {
  audit: <AuditTagIcon />,
  chain: <ChainTagIcon />,
  coins: <CoinsTagIcon />,
  discord: <DiscordTagIcon />,
  dollar: <DollarTagIcon />,
  dollar2: <Dollar2TagIcon />,
  folders: <FoldersTagIcon />,
  funding: <FundingTagIcon />,
  github: <GithubTagIcon />,
  link: <LinkTagIcon />,
  linkedIn: <LinkedInTagIcon />,
  location: <LocationTagIcon />,
  run: <RunTagIcon />,
  salary: <SalaryTagIcon />,
  senior: <SeniorTagIcon />,
  shoppingBag: <ShoppingBagTagIcon />,
  skull: <SkullTagIcon />,
  teamSize: <TeamSizeTagIcon />,
  twitter: <TwitterTagIcon />,
  utc: <UtcTagIcon />,
  website: <WebsiteTagIcon />,
};

// TEMPORARY: map tag to icon
export const getTagIcon = (key: keyof typeof tagIconMap) => tagIconMap[key];
