import {
  TEXT_ROUTE_SECTION_JOBS,
  TEXT_ROUTE_SECTION_ORGANIZATION,
  TEXT_ROUTE_SECTION_PROJECTS,
  TEXT_ROUTE_SECTION_REPOSITORIES,
  TEXT_ROUTE_TAB_COMPETITORS,
  TEXT_ROUTE_TAB_DETAILS,
  TEXT_ROUTE_TAB_JOBS,
  TEXT_ROUTE_TAB_ORGANIZATION,
  TEXT_ROUTE_TAB_PROJECTS,
  TEXT_ROUTE_TAB_REPOSITORIES,
} from '~/shared/core/constants';

export type RouterPush = (
  url: string,
  options?: { shouldScroll?: boolean; shallow?: boolean },
) => void;

export type RouteSection =
  | typeof TEXT_ROUTE_SECTION_JOBS
  | typeof TEXT_ROUTE_SECTION_ORGANIZATION
  | typeof TEXT_ROUTE_SECTION_PROJECTS
  | typeof TEXT_ROUTE_SECTION_REPOSITORIES;

export type RouteTab =
  | typeof TEXT_ROUTE_TAB_DETAILS
  | typeof TEXT_ROUTE_TAB_JOBS
  | typeof TEXT_ROUTE_TAB_ORGANIZATION
  | typeof TEXT_ROUTE_TAB_PROJECTS
  | typeof TEXT_ROUTE_TAB_COMPETITORS
  | typeof TEXT_ROUTE_TAB_REPOSITORIES;
