export const PROFILE_RIGHT_PANEL_TAB = {
  TECHNOLOGIES_USED: 'Technologies Used',
  YOUR_CONTRIBUTION: 'Your Contribution',
  SALARY: 'Salary',
  RATING: 'Rating',
  YOUR_REVIEW: 'Your Review',
};

export const PROFILE_RIGHT_PANEL_TABS = {
  REPOSITORIES: [
    PROFILE_RIGHT_PANEL_TAB.TECHNOLOGIES_USED,
    PROFILE_RIGHT_PANEL_TAB.YOUR_CONTRIBUTION,
  ],
  ORG_REVIEWS: [
    PROFILE_RIGHT_PANEL_TAB.SALARY,
    PROFILE_RIGHT_PANEL_TAB.RATING,
    PROFILE_RIGHT_PANEL_TAB.YOUR_REVIEW,
  ],
};

export const MAX_CONTRIBUTION_SUMMARY_LENGTH = 500;
