export const FILTER_KIND = {
  RANGE: 'RANGE',
  SINGLE_SELECT: 'SINGLE_SELECT',
  MULTI_SELECT: 'MULTI_SELECT',
  MULTI_SELECT_WITH_SEARCH: 'MULTI_SELECT_WITH_SEARCH',
} as const;

export const FILTER_CONFIG_KEY_SET = new Set([
  'publicationDate',
  'minSalaryRange',
  'maxSalaryRange',
  'minTeamSize',
  'maxTeamSize',
  'minHeadCount',
  'maxHeadCount',
  'minTvl',
  'maxTvl',
  'minMonthlyVolume',
  'maxMonthlyVolume',
  'minMonthlyFees',
  'maxMonthlyFees',
  'minMonthlyRevenue',
  'maxMonthlyRevenue',
  'minAudits',
  'maxAudits',
  'hacks',
  'fundingRounds',
  'tech',
  'organizations',
  'chains',
  'projects',
  'categories',
  'seniority',
  'locations',
  'mainNet',
  'token',
  'order',
  'orderBy',
  'query',
]);
