// Blocked terms
export const BLOCKED_TERM_DTYPE = 'BLOCKED_TERM';
export const BLOCKED_TERMS_DTYPE = 'BLOCKED_TERMS';
export const BLOCKED_TERMS_INIT_DTYPE = 'BLOCKED_TERMS_INIT';
export const BLOCKED_TERMS_INIT_TECHS_DTYPE = 'BLOCKED_TERMS_INIT_TECHS';
export const SET_BLOCKED_TERMS_OK_DTYPE = 'SET_BLOCKED_TERMS_OK';
export const UNSET_BLOCKED_TERMS_OK_DTYPE = 'UNSET_BLOCKED_TERMS_OK';
