// Blocked terms
export const BLOCKED_TERM_DTYPE = 'BLOCKED_TERM';
export const BLOCKED_TERMS_DTYPE = 'BLOCKED_TERMS';
export const BLOCKED_TERMS_INIT_DTYPE = 'BLOCKED_TERMS_INIT';
export const BLOCKED_TERMS_INIT_TECHS_DTYPE = 'BLOCKED_TERMS_INIT_TECHS';
